name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  CodeQL-Build:
    name: Code Quality
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    #  TODO: Re-enable the following lines after adding some code to analyze
    # - name: Initialize CodeQL
    #   uses: github/codeql-action/init@v1

    # # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # # If this step fails, then you should remove it and run the build manually (see below)
    # - name: Autobuild
    #   uses: github/codeql-action/autobuild@v1

    # - name: Perform CodeQL Analysis
    #   uses: github/codeql-action/analyze@v1
  Build:  
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - run: dotnet build <my project>

  Resharper:
    name: Resharper
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Do something awesome
      run: echo "Something awesome pending"